#!/usr/bin/env bash
# docker/start-container
set -e

echo "===> Installing dependencies..."
composer install --no-dev --no-interaction --optimize-autoloader

echo "===> Generating key..."
php artisan key:generate --force

echo "===> Caching config..."
php artisan config:cache

echo "===> Caching routes..."
php artisan route:cache

echo "===> Caching views..."
php artisan view:cache

echo "===> Running migrations..."
php artisan migrate --force

echo "===> Starting PHP-FPM..."
exec php-fpm